### ISSUE TITLE
Can this plugin do directional splitting?

### ISSUE THREAD

**Issue by DEliasVCruz** [nyngwang/NeoZoom.lua#23]
In normal splits you can do something like:

- `:above vsp`: Create a split to the right
- `:below vsp`: Create a split to the left
-  `:above split`: Create a split above
-  `:below split`: Create a split below

Is this still possible with the `NeoSplit` and `NeoVSplit` commands?

**Comment by nyngwang** [comment]
@DEliasVCruz Sorry for my (very!) late respond first.

> Is this still possible with the `NeoSplit` and `NeoVSplit` commands?

Do you mean opening the floating window with some preset offset and height/width?
