### ISSUE TITLE
Issues when working with bufferline instead of tabline

### ISSUE THREAD

**Issue by DEliasVCruz** [nyngwang/NeoZoom.lua#24]
Based on the `README` and some quick testing. This plugin seems to be based around working with the tabline. But I found a niche problem if a user such as my self does not use the `:tab` feature but instead relies on some `bufferline` plugin. 

If for some reason the bufferline is not loaded at startup but is instead lazy loaded on some module call or editor event. Then if one where to create splits with the `NeoSplit` or `NeoVsplit` commands. Then upon invoking `NeoZoomToggle` the bufferline breaks as the tabline appears. Not until the bufferline plugin gets loaded do things come back to normal

This does not happens if splits are created normally, and only use `NeoZoomToggle` or if the bufferline plugins is loaded before any call to `NeoSplit` or `NeoVsplit`

I know is a very edge case issue, but I thought it would be good to report it

**Comment by nyngwang** [comment]
Closing issues on the old version(now in branch `neo-zoom-original`). Recommend you to try the current `main` one which facilitates a floating window, and it only has one command `NeoZoomToggle`.
