### ISSUE TITLE
Error: neo-zoom.lua:29: attempt to index local 'opt' (a nil value)

### ISSUE THREAD

**Issue by stephane-klein** [nyngwang/NeoZoom.lua#32]
I have this error with `de0e27a3e619ed3f79232ba8daf0ae1a8e92bfea` changeset on Neovim version 0.7.2:

```
packer.nvim: Error running config for NeoZoom.lua: ...nvim/site/pack/packer/start/NeoZoom.lua/lua/neo-zoom.lua:29: attempt to index local 'opt' (a nil value)
```

I wounder if this is an error of my part or a `ZeoZoom.lua` bug :thinking:

**Comment by stephane-klein** [comment]
An idea @nyngwang

**Comment by Irubataru** [comment]
I got the same and it seems to be because `setup` requires an array, it cannot be empty. I.e. you have to do `require("neo-zoom").setup({})`, you cannot just do `require("neo-zoom").setup()` like most other plugins.

**Comment by gstokkink** [comment]
Ran into this as well, lrubataru's fix worked.
