### ISSUE TITLE
Calling :q inside a zoom window gives invalid window id

### ISSUE THREAD

**Issue by Irubataru** [nyngwang/NeoZoom.lua#33]
As the title says, `:q` gives an error when called in a zoom

```
Error detected while processing WinEnter Autocommands for "*":
Error executing lua callback: ...nvim/site/pack/packer/start/NeoZoom.lua/lua/neo-zoom.lua:92: Invalid window id: 1003
stack traceback:
        [C]: in function 'nvim_win_get_buf'
        ...nvim/site/pack/packer/start/NeoZoom.lua/lua/neo-zoom.lua:92: in function <...nvim/site/pack/packer/start/NeoZoom.lua/lua/neo-zoom.lua:87>
```

This might make sense, but the muscle memory of calling `:q` to close something is quite hard to get rid off.

**Comment by nyngwang** [comment]
@Irubataru Just reproduced it right now. Let me fix it now. (I just finished clean up 200+ notifications)

**Comment by nyngwang** [comment]
@Irubataru Sorry for tagging you again. Now everything should work and the example in the README.md is update-to-date with these changes. DEMO:
