### ISSUE TITLE
Auto unfocus when navigating to other buffers

### ISSUE THREAD

**Issue by jeeeem** [nyngwang/NeoZoom.lua#44]
Is there a way to do this?

EDIT: And maybe also when splitting planes 'cos i'm having this behavior

![image](https://user-images.githubusercontent.com/51053482/213515257-51af16ff-704d-446b-90a6-4f033302f472.png)

**Comment by nyngwang** [comment]
Yes, this is possible and I actually implemented this before and discarded it. I will create an option for this.

**Comment by jeeeem** [comment]
> Yes, this is possible and I actually implemented this before and discarded it. I will create an option for this.

Please do, it will very efficient for us users to use it than manually pressing the toggle key. thanks

**Comment by nyngwang** [comment]
@jeeeem Hi, thanks for your waiting. It turns out to be a lot trickier than I assumed. Now it's done and you just enable it like this:

```lua
setup {
  disable_by_cursor = true,
}
```
And you will be fine calling `NeoZoomToggle`. But then the example config I provided in README is invalid currently, I will update it later.

**Comment by nyngwang** [comment]
@jeeeem FYI: `disable_by_cursor` is removed in ab69e31(can remove this option in `setup`), and you don't have to worry about clicking outside on zoom in by d4436f8.

**Comment by nyngwang** [comment]
9f54eb9: there is no `autocmd` anymore so, unfortunately, now you have to call `NeoZoomToggle` again so the cursor will jump back to the zoom-in window. After that you call `NeoZoomToggle` again so it will be closed.

**Comment by jeeeem** [comment]
Thanks for updating me although you don't have to do that. And I'm okay with the changes, I see myself toggling the zoom than auto zooming in/out so I don't have a problem with the change.
