### ISSUE TITLE
Bug: Zoom-out with `disable_by_cursor = true `  will navigate the cursor back to first line 

### ISSUE THREAD

**Issue by jeeeem** [nyngwang/NeoZoom.lua#52]
Using the normal toggle, the cursor is still the same line number when you zoom-out but using `C-h/j/l/k` (vim navigation) will zoom out the current buffer back to the first line.

Is this normal behavior? Shouldn't be go back to the current line also just like the normal toggling behavior?

**NVIM Version:** NVIM v0.9.0-dev-701+g34b973b1d

**Comment by nyngwang** [comment]
Hi! Thank you for the careful-minded observation! I just confirmed this (I did something wrong during adding features.) (was sleeping so late in reply.)
