### ISSUE TITLE
did_zoom not working on popup

### ISSUE THREAD

**Issue by petobens** [nyngwang/NeoZoom.lua#55]
Hi!
I have the following mapping to close floating windows with `q` but to toggle neozoom if the floating window is zoomed:
```lua
u.keymap('n', 'q', function()
    if vim.api.nvim_win_get_config(0).zindex then
        if require('neo-zoom').did_zoom() then
            vim.cmd('NeoZoomToggle')
        else
            vim.cmd('close')
        end
    end
end)
```
The problem with this is that if I get into a popupmenu (such as gitsigns) then did_zoom believes this  a "zoomed" window and "NeoZoomToggle" gets called (instead of the expected `close`). Can get_zoom be changed so it works correctly for this case?

![zoom](https://user-images.githubusercontent.com/2583971/216822781-b4dc1558-7e30-4541-844e-af512372dbd5.gif)

**Comment by nyngwang** [comment]
Try this:

```lua
u.keymap('n', 'q', function()
    if require('neo-zoom').did_zoom()[1] then
        vim.cmd('NeoZoomToggle')
        return
    end
    if vim.api.nvim_win_get_config(0).zindex then
        vim.cmd('close')
    end
end)
```

**Comment by petobens** [comment]
It does! Thank you!
