### ISSUE TITLE
Issue with 2 tabs without splits

### ISSUE THREAD

**Issue by neriusmika** [nyngwang/NeoZoom.lua#6]
If you have 2 tabs and activate NeoZoom in the 1st tab without any splits, then the 1st tab just closes and switches to the second tab.

The expected behavior would be to do nothing.

**Comment by nyngwang** [comment]
Thanks for the report, let me fix it now!

**Comment by nyngwang** [comment]
Really a nice catch! It's a typo, sorry if it cause some inconvenience for your work 🙇

**Comment by neriusmika** [comment]
Thanks, by the way, if there is only one tab without splits, NeoZoom opens the second tab which looks exactly the same. Of course, it's not a big issue, but probably a separate tab in such cases is not necessary.

**Comment by nyngwang** [comment]
> NeoZoom opens the second tab which looks exactly the same

That is a breaking change I made days ago. Let me rethink about it. (the intention is that I was too lazy to type `:tab split` myself when I wanted to create a new tab)

**Comment by neriusmika** [comment]
Actually, if it breaks something, then it's fine as is. Just seems a little strange :)

Thank you for a great and useful plugin!

**Comment by neriusmika** [comment]
:lithuania: :heart: :taiwan:
