### ISSUE TITLE
first usage error

### ISSUE THREAD

**Issue by Sarna555** [nyngwang/NeoZoom.lua#67]
I've installed the plugin using packer and run :NeoZoomToggle
![image](https://user-images.githubusercontent.com/5701624/219646693-b854dbc5-86b1-4085-a32f-9d1f0940b105.png)

**Comment by nyngwang** [comment]
@Sarna555 Can you paste your `setup` for me?

**Comment by Sarna555** [comment]
@nyngwang Anything specific? I've recently started using lunar vim
```
$ lvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az183-550
```

and I've just only added

```lua
lvim.plugins = {
    {"nyngwang/NeoZoom.lua"},
}
```

**Comment by nyngwang** [comment]
@Sarna555 I didn't use lunar vim before, but I guess that you will have to call the `setup` function yourself as per the README [section](https://github.com/nyngwang/NeoZoom.lua#keymapset-example):

```lua
require('neo-zoom').setup { ... }
```

**Comment by nyngwang** [comment]
By 0daba34 you should now see the new error message, closing.

**Comment by nyngwang** [comment]
@Sarna555 Just searched it for you. You should add more key-value pairs for each `{table}` inside `lvim.plugins`, see below. Ref. from [LunarVim/LunarVim#3723-comment](https://github.com/LunarVim/LunarVim/issues/3723#issuecomment-1397632194):

```lua
lvim.plugins = {
  {
    "lervag/vimtex",
    ft = "tex", -- without ft, it's not working too
    config = function()
      vim.cmd("call vimtex#init()")
    end,
  },
}
```

**Comment by Sarna555** [comment]
@nyngwang ok, thank you! I've been just stuck in the mud assuming that "setup" with default arguments is called always implicitly.
