### ISSUE TITLE
Feature request: lualine integration

### ISSUE THREAD

**Issue by onelesd** [nyngwang/NeoZoom.lua#7]
It would be helpful to have an indicator of a zoomed in pane, lest we forget. One way to integrate is like so:

https://github.com/nvim-lualine/lualine.nvim#lua-expressions-as-lualine-component

**Comment by onelesd** [comment]
Another idea on indicating zoom that I like from emacs: https://github.com/emacsorphanage/zoom-window

**Comment by nyngwang** [comment]
Great idea. Two points came into my mind are:

- This reminds me of a drawback of my current implementation: on zoom-in, __change the tab-order__ will cause the starting point (let's call it _parent_) to be forgotten.
- For the latter one: I can imagine that the result will be great. But then I will have to reconsider when to allow nested zoom-in (or even disallow it?), or one will have the 2nd, 3rd, ..., tabs all got colored.

**Comment by nyngwang** [comment]
After some rethink I think this is a great idea to discard nested zoom-in:

- What I call nested zoom-in is indeed a result of no-rule: I allow any zoom-in as long as the starting window (1) is on a tab with more than one window (2) it's on the first tab.
- Nested zoom-in is indeed a complicated usecase, but it can be simplified if:
   -  We discard the nested zoom-in. When a user sees the statusline got colored, then one immediately knows that __the only__ behaviour now is back to the starting window.
   - Provide another mechanism for "nested zoom-in" (or simply call it "creating a new adjacent tab after the current one"). Now we have both.

**Comment by nyngwang** [comment]
Some decisions made during implementation:

- On zoom-in, the entire tab will be marked as zoom-in-tab. We discard the entire zoom-in-tab on zoom-out from __any__ window in the zoom-in-tab.

**Comment by nyngwang** [comment]
The pre-requisite has been completed for the coloring, I will implement it in another PR :)

**Comment by nyngwang** [comment]
@onelesd Closing issues on the old version. The new version facilitates a floating window for zooming. This makes the zoom-in window very special and achieves what you have described in this issue.
