### ISSUE TITLE
Can't get window to center?

### ISSUE THREAD

**Issue by Integralist** [nyngwang/NeoZoom.lua#85]
This is my config...

```lua
{
    "nyngwang/NeoZoom.lua",
    config = function()
        require('neo-zoom').setup({})
        vim.keymap.set("", "<leader><leader>z", "<Cmd>NeoZoomToggle<CR>", {desc = "full screen active window"})
    end
}
```

But this is how the zoomed window is displayed?

<img width="1920" alt="Screenshot 2023-10-05 at 08 00 26" src="https://github.com/nyngwang/NeoZoom.lua/assets/180050/82c40958-b6cb-4d85-bfd9-b06bb8289a38">

Any ideas what I might be doing wrong?

Thanks!

**Comment by niderhoff** [comment]
the default config sets an offset (compare readme). You might want to change that.

**Comment by Integralist** [comment]
Hi @niderhoff 

Setting `left = 0` did the trick...

```
require('neo-zoom').setup({
    winopts = {left = 0, width = 150, height = 0.80}
})
```
