### ISSUE TITLE
Preserve 'nowrap' on toggling

### ISSUE THREAD

**Issue by mxgrn** [nyngwang/NeoZoom.lua#87]
When I return from the zoom mode back to the original, the `nowrap` window setting gets reset.

Expected behavior: the `nowrap` setting on the window should always be preserved when toggling the zoom.

**Comment by nyngwang** [comment]
One of the original ideas is to provide a sandbox buffer in the zoom-in mode, i.e. everything will be reset on zoom-out. If your original buffer has the `nowrap` set, this plugin won't touch it.

**Comment by mxgrn** [comment]
But this is exactly what "preserve" means: don't change it. And as far as I remember, it was _always_ getting reset.
As I no longer use this, feel free to close.
